var config = {
    texts: [
        "Halo Nata...",      
        "Gimana kabarnya? Semoga sehat selalu yaw...",  
        "Anw selamat bertambah umur ya cuyyy!",
        "Sekalianlah, selamat merintis harapan di tahun 2025 ini :D",
        "Semoga segala keinginan yang belum tersampaikan di 2024 lalu,",
        "Dapat diijabah dan dikabulkan di tahun ini, aamiin...",
        "Oh iya, aku ada pengakuan ki wkwk :v",
        "Iki sebenere wis ket jaman sak durunge pindah ning kancab sih...",
        "Tapi durung kesampaian ngomong XD",
        "Tenang, santai, gausah dredeg :D",
        "Aku mung pingin ngomong kalau...",
        "Bau parfummu itu Nat, masyaAllah harum semerbak, nempel dia sampai kost-an hehe XD",
        "Its okeyyy, jadi obat anti penat di TGS :D",
        "Ah selain itu, aku nyuwun ngapunten ya, akhir-akhir iki buat risih hehe...",
        "Ya sebenarnya sejak dulu sih sering merepotkannya :v",
        "Tapi bener katamu Nat, jujur cukup kesepian aku ning kene wkwk XD",
        "Semua rekan kerjaku di UG Survey wis berkeluarga & paling muda ki angkatan 2013 wkwk",
        "Ya nyambung-nyambung aja sih, cuma bahasan humor & sebagainya agak beda zaman :)",
        "Juga beban kerjaan lumayan berat ternyata wkwk :v",
        "Tapi aman kok, cuma butuh cerita-cerita dikit buat lapangkan pikiran...",
        "So, makasih ya, sudah meluangkan waktumu hehe :)",
        "Eh, makasih juga atas segala bantuanmu Nat, baik di perkuliahan maupun di TGS!",
        "Serius, terimakasih ya Nata :)",
        "Mungkin sementara ini dulu unek-unek ku XD",
        "Yang penting sehat terus ya di sana...",
        "Semangat para pejuang Rp!",
        "Semoga selalu dilancarkan urusannya...",
        "Semoga dapat bersua lagi di lain kesempatan.",
        "~Andi",
    ],
    
    imgs: {
        "Halo Nata...": "./imgs/Nata.png",
        
    },
    desc: {
        turn_on: "Nyalakan lampu?",
        play: "Gasss musik?",
        bannar_coming: "Yuk dekorasi!",
        balloons_flying: "Terbangkan balon yap!",
        cake_fadein: "Ehem, kue virtual?",
        light_candle: "Nyalakan lilin ya...",
        wish_message: "Panjang umurrr!",
        story: "Secercah pesan :)",
    }
};
