var config = {
    texts: [
        "Halo Kak 'Someone'...",      
        "Gimana kabarnya? Semoga sehat selalu ya...",  
        "Anw selamat bertambah umur ya Kak!",
        "Sekalianlah, selamat merintis harapan baru di pertengahan tahun 2025 ini :D",
        "Semoga segala keinginan yang belum tersampaikan di 2024 lalu,",
        "Dapat diijabah dan dikabulkan di tahun ini, aamiin...",
        "Oh iya, maaf ya kirimnya telat beberapa hari :')",
        "Soalnya aku baru baca kiriman Kak Someone tadi pagiii...",
        "Tapi semoga Kakak suka ya...",
        "Ummm, bolehkah aku memberikan sepatah-dua patah kata?",
        "Bukan hanya untuk Kakak saja sih,",
        "Namun kata-kata ini juga berlaku untukku hahaha :)",
        "So sekali lagi, selamat ulang tahun yaaa...",
        "Mungkin tidak banyak yang mengingat,",
        "Akan tetapi, aku berharap Kakak selalu dikelilingi kebaikan,",
        "Walau dunia terkadang terasa sunyi :)",
        "Kak Someone juga manusia...",
        "Sah-sah saja merasa kecewa, sedih, atau kesepian...",
        "Tapi ingat, Kak Someone tetap berarti...",
        "Dan dirimu selalu pantas untuk dirayakan :)",
        "Jangan matikan harapanmu karena orang lain ya Kak :)",
        "Memang seringkali dunia ini terasa sepi,",
        "Namun yakinlah kalau Kak Someone 'tidak pernah' sendiri, okey(?) :)",
        "Mungkin sementara ini dulu secercah pesan dariku...",
        "Btw kita saat ini belum saling kenal ya hehehe",
        "Semoga kedepannya kita bisa berteman ya Kak...",
        "Yang penting sehat terus ya di sana...",
        "Semoga selalu dilancarkan urusannya...",
        "Semoga dapat bersua di lain kesempatan.",
        "~Quora Reader, Andi",
    ],
    
    imgs: {
        "Halo Kak Someone...": "./imgs/someone.jpeg",
        
    },
    desc: {
        turn_on: "Mau nyalaian lampu?",
        play: "Coba putar musik?",
        bannar_coming: "Hayuuuk dekorasi!",
        balloons_flying: "Terbangkan balon yap!",
        cake_fadein: "Ehem, kue virtual?",
        light_candle: "Nyalakan lilin ya...",
        wish_message: "Panjang umurrr!",
        story: "Secercah pesan :)",
    }
};
