var config = {
    texts: [
        "Halo Nata...",      
        "Gimana kabarnya? Semoga sehat selalu yaw...",  
        "Eh iya, anw selamat bertambah umur ya cuyyy!",
        "Sekalianlah, selamat merintis harapan di tahun 2025 ini :D",
        "Semoga segala keinginan yang belum tersampaikan di 2024 lalu,",
        "Dapat diijabah di tahun ini, aamiin...",
        "Oh iya, aku ana pengakuan ki wkwk :v",
        "Iki sebenere wis ket jaman sak durunge pindah ning kancab sih...",
        "Tapi durung kesampaian ngomong XD",
        "Tenang, santai, gausah dredeg :D",
        "Aku mung pingin ngomong yen...",
        "Bau parfummu Nat, masyaAllah harum semerbak, nempel dia sampai kost-an hehe...",
        "Its okeyyy, jadi obat anti penat di TGS :D",
        "Ah selain itu, aku nyuwunn ngapunten ya, akhir-akhir iki gawe risih hehe...",
        "Soale bener katamu Nat, jujur wae kesepian aku ning kene wkwk XD",
        "Semua rekan kerjaku wis berkeluarga & paling muda ki angkatan 2013 wkwk",
        "Ya nyambung-nyambung aja sih, cuma bahasan humor & sebagainya agak beda,",
        "Juga beban kerjaan lumayan berat ternyata wkwk :v",
        "Tapi amannn, hanya itu aja, butuh cerita-cerita buat lapangkan pikiran :v",
        "So, makasih ya, sudah meluangkan waktumu hehe :)",
        "Eh, makasih juga atas segala bantuanmu Nat, baik di perkuliahan maupun di TGS!",
        "Yang penting sehat terus ya di sana...",
        "Semangat pejuang Rp!",
        "Semoga selalu dilancarkan urusannya...",
        "Semoga dapat bersua lagi di lain kesempatan yow.",
        "~Andi",
    ],
    
    imgs: {
        "Halo Nata...": "./imgs/irba.jpg",
        
    },
    desc: {
        turn_on: "Nyalakan lampu?",
        play: "Nyalakan musik?",
        bannar_coming: "Yuk kita dekorasi!",
        balloons_flying: "Terbangkan balonnn!",
        cake_fadein: "Ehem, kue virtual?",
        light_candle: "Nyalakan lilin ya...",
        wish_message: "Panjang umurrr!",
        story: "Secercah pesan :)",
    }
};
